import { Link } from 'react-router-dom';
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { useCartStore } from '../store/cartStore';

export const Cart = () => {
  const { items, removeItem, updateQuantity, clearCart } = useCartStore();
  const totalAmount = items.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const totalItems = items.reduce((sum, item) => sum + item.quantity, 0);

  if (items.length === 0) return <div className="mx-auto flex max-w-md flex-col items-center py-16 text-center"><div className="mb-5 flex h-20 w-20 items-center justify-center rounded-full bg-[#e8f5e4] text-[#55b978]"><ShoppingBag size={34} /></div><h1 className="text-2xl font-extrabold tracking-[-0.04em] text-[#26322b]">Your cart is empty</h1><p className="mt-2 text-sm leading-6 text-[#7b867e]">Add a few fresh favourites and they will appear here.</p><Link to="/" className="focus-ring mt-7 rounded-xl bg-[#55b978] px-6 py-3 text-sm font-bold text-white">Start shopping</Link></div>;
  return <div className="animate-rise-in mx-auto max-w-5xl"><div className="mb-6 flex items-center justify-between"><h1 className="text-2xl font-extrabold tracking-[-0.05em] text-[#26322b]">My Cart</h1><button onClick={clearCart} className="focus-ring rounded-lg text-xs font-bold text-[#d4795b]">Clear all</button></div><div className="grid gap-5 lg:grid-cols-[1fr_340px] lg:items-start"><section className="space-y-2">{items.map((item) => <div key={item.id} className="flex gap-3 rounded-xl border border-[#edf0ec] bg-white p-3"><Link to={`/product/${item.id}`} className="h-20 w-20 shrink-0 overflow-hidden rounded-lg bg-[#f2f6ef]"><img src={item.image} alt={item.name} className="h-full w-full object-cover" /></Link><div className="flex min-w-0 flex-1 flex-col"><div className="flex justify-between gap-2"><Link to={`/product/${item.id}`} className="focus-ring line-clamp-2 rounded text-sm font-bold leading-5 text-[#26322b]">{item.name}</Link><button onClick={() => removeItem(item.id)} className="focus-ring h-fit rounded-lg p-1 text-[#b8c0ba]" aria-label={`Remove ${item.name}`}><Trash2 size={16} /></button></div><p className="text-[10px] text-[#9ca69e]">{item.category} · {item.unit}</p><div className="mt-auto flex items-center justify-between"><p className="text-sm font-extrabold text-[#26322b]">${(item.price * item.quantity).toFixed(2)}</p><div className="flex items-center rounded-lg border border-[#e2eae0]"><button onClick={() => updateQuantity(item.id, item.quantity - 1)} className="focus-ring p-1.5 text-[#77827a]" aria-label={`Decrease quantity of ${item.name}`}><Minus size={13} /></button><span className="w-6 text-center text-xs font-bold">{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)} disabled={item.quantity >= item.stock} className="focus-ring p-1.5 text-[#77827a] disabled:opacity-40" aria-label={`Increase quantity of ${item.name}`}><Plus size={13} /></button></div></div></div></div>)}</section><aside className="rounded-xl border border-[#edf0ec] bg-white p-4 lg:sticky lg:top-6"><h2 className="text-base font-extrabold text-[#26322b]">Order summary</h2><div className="mt-4 space-y-3 border-b border-[#edf2eb] pb-4 text-xs text-[#7b867e]"><div className="flex justify-between"><span>Subtotal ({totalItems} items)</span><b className="text-[#26322b]">${totalAmount.toFixed(2)}</b></div><div className="flex justify-between"><span>Delivery</span><b className="text-[#55b978]">Free</b></div></div><div className="flex justify-between py-4 text-base font-extrabold text-[#26322b]"><span>Total</span><span>${totalAmount.toFixed(2)}</span></div><Link to="/checkout" className="focus-ring flex items-center justify-center gap-2 rounded-xl bg-[#55b978] py-3.5 text-sm font-bold text-white">Go to Checkout <ArrowRight size={16} /></Link></aside></div></div>;
};
